### PR TITLE
Correcting the field templates

### PR DESCRIPTION
**Pull request by hbogaards**
Corrected the field templates to repair the `<f:display>` rendering.
And removed the `_wrapper` templates to enable overriding them in an application that uses the joda-time plugin.

I tried creating a test that checked the rendering of the `<f:field>` and `<f:display>` tag with the different joda-time types, but failed so far at writing the tests

### CODE REVIEW

**Comment by sbglasius** [comment]
Please see, if you can get the tests passing. Thanks.

**Comment by hbogaards** [comment]
I am trying, but I don't understand why my changes make the tests fail.

Even if I check out the 2.0.0 tag and build it locally those tests fail

**Comment by sbglasius** [comment]
Ok, perhaps it's not an issue created by you.... I just became part of the gpc

**Comment by hbogaards** [comment]
When I upgrade the joda-time library to version 2.9.2 all `FormattingTagLibTests` tests succeed.
But on my Windows machine still 2 `Html5InputTagLibSpec` tests fail

**Comment by hbogaards** [comment]
Is there a way I can see the test report of this build?

**Comment by sbglasius** [comment]
Your PR has been merged into https://github.com/gpc/joda-time/pull/26 and will go in the next release.

**Pull request closed without merging**
